### ISSUE TITLE
Setup in Window 11 (without WSL)

### ISSUE THREAD

**Issue by sachin0034** [microsoft/call-center-ai#255]
Set up the project on my local Windows 11 system but encountered issues
I have been setting up this project on my local system running Windows 11. However, I am facing some issues that need to be resolved in order for me to contribute effectively. Can anyone help me resolve these issues?

**Comment by clemlesne** [comment]
Hello, can you detail your issues? What are you trying to do? What is the detailed error? What's the logs?

**Comment by clemlesne** [comment]
GitHub Codespaces support haas been added: https://codespaces.new/microsoft/call-center-ai?quickstart=1. You can use this environment to code in this automatically configured environment, without using your laptop.

**Comment by sachin0034** [comment]
![Screenshot (28)](https://github.com/user-attachments/assets/2ff53788-9994-4fe6-815a-3f2e0bd36e2f)
Unable to access this url.
