### ISSUE TITLE
Programmatic calls and output gathering

### ISSUE THREAD

**Issue by renasserhat** [microsoft/call-center-ai#258]
Can I improve this a little and create a list for 50 people and have them call 50 people and get information from them and save that information to me?

**Comment by clemlesne** [comment]
If I understand well, you want to call a list of people, gather data, and get back the data from those conversations. Right?

If yes, that's totally feasible. Call 50 times the API `POST /call` to create new outbound calls with the same task and claim fields. Then, fetch the API `GET /call` to get the status of those calls.

The limitation is, for now, there is no option to be alerted for a completed call. How to say if a call is completed (technically -- the call exited, or functionally -- the task is completed)? How to send the event? Those points have not yet been addressed.

**Comment by clemlesne** [comment]
Closing for now. Do not hesitate to reopen for more questions!
