### ISSUE TITLE
Detail draft on Deployment for Local/remote 

### ISSUE THREAD

**Issue by asangohi09** [microsoft/call-center-ai#266]
Hello,
can you provided with a detail draft for setting up the project on local setup as well as on the remote setup with some details steps involved and changes that are required to be made.
Also if you can provide with a particular browser login URL or on which port we can check weather the application is working properly or not.
Also any mentions that we need to particularly replace in the local.setting.json file so the deployment to work smoothly.
Also can you mention steps after the `make dev` step for debug as it is not properly drafted there.

Rest the project is very wonderfully and easy to integrate to the applications.

**Comment by asangohi09** [comment]
I made some changes to the current setup in the Makefile and when running the `make dev ` command then I am getting the following errors. I have shared the logs below. Please find the logs below:


`make dev
/bin/sh: 1: devtunnel: not found
VERSION=10.0.0+20240714135803 PUBLIC_DOMAIN= func start --verbose
Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]
Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]
Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]
SkipInProcessHost compilation symbol is not defined.
local.settings.json file not found. Path searched:/home/flexperttechavtarAI/call-center-ai/local.settings.json
FUNCTIONS_INPROC_NET8_ENABLED app setting is not enabled in local.settings.json

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %


Azure Functions Core Tools
Core Tools Version:       4.0.5907 Commit hash: N/A +807e89766a92b14fd07b9f0bc2bea1d8777ab209 (64-bit)
Function Runtime Version: 4.834.3.22875

Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]
Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]
Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]
[2024-07-17T09:21:13.587Z] The 'FUNCTIONS_WORKER_RUNTIME' setting is required. Please specify a valid value. See https://go.microsoft.com/fwlink/?linkid=2257963 for more information. The application will continue to run, but may throw an exception in a future release.
[2024-07-17T09:21:13.675Z] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
[2024-07-17T09:21:18.561Z] Host lock lease acquired by instance ID '0000000000000000000000002D6D3A8D'.
`


In this I am getting one error which is dev tunnel not found which when tried to install it is not working and configured properly. getting error like `apt_pkg` broken & not found .


Your help on this part would be much appreciated.


Thanks

**Comment by clemlesne** [comment]
Since 3241b0e236a75bacf097dd648062a31181020056 the installation procedure should be clearer. Does it help you?

**Comment by clemlesne** [comment]
Closing for now. Do not hesitate to reopen for more questions!
